language: scala

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND repo=kellydavid/scala-server-lambda

jobs:
  include:
    - stage: test
    - name: compile and test
      script: sbt +compile +test
    # - name: formatting
    # script: ./bin/scalafmt --test
    - stage: release # Only runs if previous stages pass
      script: sbt version ci-release
